### ISSUE TITLE
Crash on string not trimmed

### ISSUE THREAD

**Issue by Armaldio** [euantorano/semver.nim#3]
Well, idk if still maintained, anyway
It's crashing when there are (at least) trailing `\n`

Crashing:
```nim
let (output, exitCode2) = execCmdEx "node -v"
let currentNodeVersion = parseVersion(output)
echo "Node: " & $currentNodeVersion
```

Not crashing:
```nim
let (output, exitCode2) = execCmdEx "node -v"
let currentNodeVersion = parseVersion(output.strip())
echo "Node: " & $currentNodeVersion
```

**Comment by euantorano** [comment]
Yeah, this is still maintained. Interesting crash, I’ll work out a fix tonight or tomorrow night and push a release, thanks.

**Comment by Armaldio** [comment]
Great 👍 

As a side note, i'm asking a question here instead of opening a new issue for that:

Can you consider `satisfies` method like at https://github.com/npm/node-semver ?

**Comment by euantorano** [comment]
I’ll have a look, that would require a bit more work to implement version constraints and ranges which I won’t get time for until the weekend at the least.

**Comment by euantorano** [comment]
Hi, I've used the following test code:

```nim
import semver

let test1 = "v1.2.3\n"
let test2 = "v1.2.3"

echo "test1: ", parseVersion(test1)
echo "test2: ", parseVersion(test2)
```

I do get an exception thrown, which is the following:

```
semver_test.nim(6)       semver_test
semver.nim(102)          parseVersion
Error: unhandled exception: (1, 6) Error: invalid token: 3 [ParseError]
```

An exception is expected, though the error message isn't correct - a newline character isn't valid content for a version string after all.

I'll look at improving the error message that is thrown, but I think this behaviour makes sense by default - perhaps I can implement a flag to ignore leading and trailing whitespace.

**Comment by Armaldio** [comment]
Indeed you're right, tho I tought that may be an error since the string is still sanitized as stated by this: 
```
When parsing versions, the module will automatically ignore any proceeding "=v" or "v", allowing it to work with user submitted versions for packages.
```

Your choice anyway ;)

**Comment by euantorano** [comment]
Ah yeah, that just means that a version like `v1.2.3` can be parsed by the library, when the semver specification says that versions should just be `1.2.3` without the `v` prefix.

I think I'll add an optional named argument to ignore whitespace, so you can do something like:

```nim
let (output, exitCode2) = execCmdEx "node -v"
let currentNodeVersion = parseVersion(output, ignoreWhitespace=true)
echo "Node: " & $currentNodeVersion
```

I'll add this tomorrow night after work as that's the first time I'll get a chance to do so.
