### ISSUE TITLE
Unreachable code

### ISSUE THREAD

**Issue by janflyborg** [euantorano/semver.nim#9]
The line 201 in semver.nim contains an unreachable statement `inc i`. Not a biggie, but I constantly see this as a warning when I build my project.

**Comment by euantorano** [comment]
Good catch, should be an easy fix. I'll try get it done tonight, thanks!

**Comment by janflyborg** [comment]
Thanks for this!

**Comment by euantorano** [comment]
Fixed in https://github.com/euantorano/semver.nim/commit/ac076d695c60943193024973b6319ef1cd451046

Version 1.2.2 tagged and released. Thanks again!
